# Generated by Django 5.2.4 on 2025-07-30 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام')),
                ('phone', models.CharField(max_length=50, verbose_name='شماره دفتر')),
                ('mobile_phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره همراه')),
            ],
            options={
                'verbose_name': 'کارمند',
                'verbose_name_plural': 'کارمند ها',
            },
        ),
    ]
