# Generated by Django 5.2.4 on 2025-07-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='department',
            field=models.CharField(choices=[('واحد اداری', 'واحد اداری'), ('رانندگان', 'رانندگان'), ('واحد تولید', 'واحد تولید'), ('واحد ای تی', 'واحد واحد'), ('سایر', 'سایر')], default='سایر', max_length=50, verbose_name='واحد'),
        ),
    ]
